module.exports = {
  seven_color_cross_fade: 'seven_color_cross_fade',
  red_gradual_change: 'red_gradual_change',
  green_gradual_change: 'green_gradual_change',
  blue_gradual_change: 'blue_gradual_change',
  yellow_gradual_change: 'yellow_gradual_change',
  cyan_gradual_change: 'cyan_gradual_change',
  purple_gradual_change: 'purple_gradual_change',
  white_gradual_change: 'white_gradual_change',
  red_green_cross_fade: 'red_green_cross_fade',
  red_blue_cross_fade: 'red_blue_cross_fade',
  green_blue_cross_fade: 'green_blue_cross_fade',
  seven_color_strobe_flash: 'seven_color_strobe_flash',
  red_strobe_flash: 'red_strobe_flash',
  green_strobe_flash: 'green_strobe_flash',
  blue_stobe_flash: 'blue_stobe_flash',
  yellow_strobe_flash: 'yellow_strobe_flash',
  cyan_strobe_flash: 'cyan_strobe_flash',
  purple_strobe_flash: 'purple_strobe_flash',
  white_strobe_flash: 'white_strobe_flash',
  seven_color_jumping: 'seven_color_jumping',
};
